name: Publish to pub.dev

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment: pub.dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.9
          channel: stable

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Publish package
        env:
          PUB_HOSTED_URL: https://pub.dev
        run: dart pub publish --force